// Autogenerated from Pigeon (v29.0.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Source contract used to generate the Dart and Kotlin Pigeon bindings.
///
/// Regenerate both platform files after changing an API method or data field.
class CameraApiConfig {
  CameraApiConfig();

  List<Object?> _toList() {
    return <Object?>[
    ];
  }

  Object encode() {
    return _toList();  }

  static CameraApiConfig decode(Object result) {
    result as List<Object?>;
    return CameraApiConfig(
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CameraApiConfig || other.runtimeType != runtimeType) {
      return false;
    }
    return true;
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CameraApiConfig()';
  }
}

/// Camera metadata shared between Flutter and the Android host.
class CameraDeviceInfo {
  CameraDeviceInfo({
    required this.id,
    required this.name,
    required this.facing,
    required this.isExternal,
    required this.previewTextureId,
  });

  String id;

  String name;

  String facing;

  bool isExternal;

  int previewTextureId;

  List<Object?> _toList() {
    return <Object?>[
      id,
      name,
      facing,
      isExternal,
      previewTextureId,
    ];
  }

  Object encode() {
    return _toList();  }

  static CameraDeviceInfo decode(Object result) {
    result as List<Object?>;
    return CameraDeviceInfo(
      id: result[0]! as String,
      name: result[1]! as String,
      facing: result[2]! as String,
      isExternal: result[3]! as bool,
      previewTextureId: result[4]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CameraDeviceInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(name, other.name) && _deepEquals(facing, other.facing) && _deepEquals(isExternal, other.isExternal) && _deepEquals(previewTextureId, other.previewTextureId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CameraDeviceInfo(id: $id, name: $name, facing: $facing, isExternal: $isExternal, previewTextureId: $previewTextureId)';
  }
}

/// Identifies the file written for one camera recording.
class CameraRecordingInfo {
  CameraRecordingInfo({
    required this.cameraId,
    required this.filePath,
  });

  String cameraId;

  String filePath;

  List<Object?> _toList() {
    return <Object?>[
      cameraId,
      filePath,
    ];
  }

  Object encode() {
    return _toList();  }

  static CameraRecordingInfo decode(Object result) {
    result as List<Object?>;
    return CameraRecordingInfo(
      cameraId: result[0]! as String,
      filePath: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CameraRecordingInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(cameraId, other.cameraId) && _deepEquals(filePath, other.filePath);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CameraRecordingInfo(cameraId: $cameraId, filePath: $filePath)';
  }
}

/// Recording durations and encoding settings passed to the Android host.
class SosCaptureSettings {
  SosCaptureSettings({
    required this.segmentDurationSeconds,
    required this.preEventDurationSeconds,
    required this.postEventDurationSeconds,
    required this.frameRate,
    required this.videoBitRate,
    required this.combinedVideoEnabled,
  });

  int segmentDurationSeconds;

  int preEventDurationSeconds;

  int postEventDurationSeconds;

  int frameRate;

  int videoBitRate;

  bool combinedVideoEnabled;

  List<Object?> _toList() {
    return <Object?>[
      segmentDurationSeconds,
      preEventDurationSeconds,
      postEventDurationSeconds,
      frameRate,
      videoBitRate,
      combinedVideoEnabled,
    ];
  }

  Object encode() {
    return _toList();  }

  static SosCaptureSettings decode(Object result) {
    result as List<Object?>;
    return SosCaptureSettings(
      segmentDurationSeconds: result[0]! as int,
      preEventDurationSeconds: result[1]! as int,
      postEventDurationSeconds: result[2]! as int,
      frameRate: result[3]! as int,
      videoBitRate: result[4]! as int,
      combinedVideoEnabled: result[5]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SosCaptureSettings || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(segmentDurationSeconds, other.segmentDurationSeconds) && _deepEquals(preEventDurationSeconds, other.preEventDurationSeconds) && _deepEquals(postEventDurationSeconds, other.postEventDurationSeconds) && _deepEquals(frameRate, other.frameRate) && _deepEquals(videoBitRate, other.videoBitRate) && _deepEquals(combinedVideoEnabled, other.combinedVideoEnabled);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'SosCaptureSettings(segmentDurationSeconds: $segmentDurationSeconds, preEventDurationSeconds: $preEventDurationSeconds, postEventDurationSeconds: $postEventDurationSeconds, frameRate: $frameRate, videoBitRate: $videoBitRate, combinedVideoEnabled: $combinedVideoEnabled)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is CameraApiConfig) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is CameraDeviceInfo) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is CameraRecordingInfo) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is SosCaptureSettings) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return CameraApiConfig.decode(readValue(buffer)!);
      case 130:
        return CameraDeviceInfo.decode(readValue(buffer)!);
      case 131:
        return CameraRecordingInfo.decode(readValue(buffer)!);
      case 132:
        return SosCaptureSettings.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Native camera operations exposed to Flutter through Pigeon.
class CameraHostApi {
  /// Constructor for [CameraHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CameraHostApi({
      BinaryMessenger? binaryMessenger, 
      String messageChannelSuffix = '', 
      })
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;


  /// Returns camera devices exposed by Android Camera2.
  Future<List<CameraDeviceInfo>> listCameras() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.camera_app.CameraHostApi.listCameras$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<CameraDeviceInfo>();
  }

  /// Requests runtime camera permission if it has not already been granted.
  Future<bool> requestCameraPermission() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.camera_app.CameraHostApi.requestCameraPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Opens previews for the requested cameras and closes unselected previews.
  Future<void> setPreviewCameras(List<String> cameraIds) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.camera_app.CameraHostApi.setPreviewCameras$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[cameraIds]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Starts rolling temporary segments for the requested camera IDs.
  Future<void> startBuffering(List<String> cameraIds, SosCaptureSettings settings) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.camera_app.CameraHostApi.startBuffering$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[cameraIds, settings]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Returns the number of pre-event seconds retained for every active camera.
  Future<int> getBufferingSeconds() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.camera_app.CameraHostApi.getBufferingSeconds$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  /// Returns the current SOS save progress from 0 to 100.
  Future<int> getSosProgress() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.camera_app.CameraHostApi.getSosProgress$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  /// Saves pre-event footage and records the configured post-event duration.
  Future<List<CameraRecordingInfo>> triggerSos() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.camera_app.CameraHostApi.triggerSos$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<CameraRecordingInfo>();
  }

  /// Stops rolling capture and deletes its temporary segments.
  Future<void> stopBuffering() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.camera_app.CameraHostApi.stopBuffering$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Releases camera and preview resources when the screen is closed.
  Future<void> releaseCameras() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.camera_app.CameraHostApi.releaseCameras$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}
