// Autogenerated from Pigeon (v29.0.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.example.camera_app

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object CameraApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * Source contract used to generate the Dart and Kotlin Pigeon bindings.
 *
 * Regenerate both platform files after changing an API method or data field.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
class CameraApiConfig  {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CameraApiConfig {
      return CameraApiConfig()
    }
  }
  fun toList(): List<Any?> {
    return listOf(
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    return true
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    return result
  }
  override fun toString(): String {
    return "CameraApiConfig()"
  }
}

/**
 * Camera metadata shared between Flutter and the Android host.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CameraDeviceInfo (
  val id: String,
  val name: String,
  val facing: String,
  val isExternal: Boolean,
  val previewTextureId: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CameraDeviceInfo {
      val id = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val facing = pigeonVar_list[2] as String
      val isExternal = pigeonVar_list[3] as Boolean
      val previewTextureId = pigeonVar_list[4] as Long
      return CameraDeviceInfo(id, name, facing, isExternal, previewTextureId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      facing,
      isExternal,
      previewTextureId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CameraDeviceInfo
    return CameraApiPigeonUtils.deepEquals(this.id, other.id) && CameraApiPigeonUtils.deepEquals(this.name, other.name) && CameraApiPigeonUtils.deepEquals(this.facing, other.facing) && CameraApiPigeonUtils.deepEquals(this.isExternal, other.isExternal) && CameraApiPigeonUtils.deepEquals(this.previewTextureId, other.previewTextureId)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.id)
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.name)
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.facing)
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.isExternal)
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.previewTextureId)
    return result
  }
  override fun toString(): String {
    return "CameraDeviceInfo(id=$id, name=$name, facing=$facing, isExternal=$isExternal, previewTextureId=$previewTextureId)"
  }
}

/**
 * Identifies the file written for one camera recording.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CameraRecordingInfo (
  val cameraId: String,
  val filePath: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CameraRecordingInfo {
      val cameraId = pigeonVar_list[0] as String
      val filePath = pigeonVar_list[1] as String
      return CameraRecordingInfo(cameraId, filePath)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      cameraId,
      filePath,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CameraRecordingInfo
    return CameraApiPigeonUtils.deepEquals(this.cameraId, other.cameraId) && CameraApiPigeonUtils.deepEquals(this.filePath, other.filePath)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.cameraId)
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.filePath)
    return result
  }
  override fun toString(): String {
    return "CameraRecordingInfo(cameraId=$cameraId, filePath=$filePath)"
  }
}

/**
 * Recording durations and encoding settings passed to the Android host.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class SosCaptureSettings (
  val segmentDurationSeconds: Long,
  val preEventDurationSeconds: Long,
  val postEventDurationSeconds: Long,
  val frameRate: Long,
  val videoBitRate: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SosCaptureSettings {
      val segmentDurationSeconds = pigeonVar_list[0] as Long
      val preEventDurationSeconds = pigeonVar_list[1] as Long
      val postEventDurationSeconds = pigeonVar_list[2] as Long
      val frameRate = pigeonVar_list[3] as Long
      val videoBitRate = pigeonVar_list[4] as Long
      return SosCaptureSettings(segmentDurationSeconds, preEventDurationSeconds, postEventDurationSeconds, frameRate, videoBitRate)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      segmentDurationSeconds,
      preEventDurationSeconds,
      postEventDurationSeconds,
      frameRate,
      videoBitRate,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SosCaptureSettings
    return CameraApiPigeonUtils.deepEquals(this.segmentDurationSeconds, other.segmentDurationSeconds) && CameraApiPigeonUtils.deepEquals(this.preEventDurationSeconds, other.preEventDurationSeconds) && CameraApiPigeonUtils.deepEquals(this.postEventDurationSeconds, other.postEventDurationSeconds) && CameraApiPigeonUtils.deepEquals(this.frameRate, other.frameRate) && CameraApiPigeonUtils.deepEquals(this.videoBitRate, other.videoBitRate)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.segmentDurationSeconds)
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.preEventDurationSeconds)
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.postEventDurationSeconds)
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.frameRate)
    result = 31 * result + CameraApiPigeonUtils.deepHash(this.videoBitRate)
    return result
  }
  override fun toString(): String {
    return "SosCaptureSettings(segmentDurationSeconds=$segmentDurationSeconds, preEventDurationSeconds=$preEventDurationSeconds, postEventDurationSeconds=$postEventDurationSeconds, frameRate=$frameRate, videoBitRate=$videoBitRate)"
  }
}
private open class CameraApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CameraApiConfig.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CameraDeviceInfo.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CameraRecordingInfo.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SosCaptureSettings.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CameraApiConfig -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is CameraDeviceInfo -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is CameraRecordingInfo -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is SosCaptureSettings -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Native camera operations exposed to Flutter through Pigeon.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface CameraHostApi {
  /** Returns camera devices exposed by Android Camera2. */
  suspend fun listCameras(): List<CameraDeviceInfo>
  /** Requests runtime camera permission if it has not already been granted. */
  suspend fun requestCameraPermission(): Boolean
  /** Opens previews for the requested cameras and closes unselected previews. */
  suspend fun setPreviewCameras(cameraIds: List<String>)
  /** Starts rolling temporary segments for the requested camera IDs. */
  suspend fun startBuffering(cameraIds: List<String>, settings: SosCaptureSettings)
  /** Returns the number of pre-event seconds retained for every active camera. */
  suspend fun getBufferingSeconds(): Long
  /** Saves pre-event footage and records the configured post-event duration. */
  suspend fun triggerSos(): List<CameraRecordingInfo>
  /** Stops rolling capture and deletes its temporary segments. */
  suspend fun stopBuffering()
  /** Releases camera and preview resources when the screen is closed. */
  suspend fun releaseCameras()

  companion object {
    /** The codec used by CameraHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      CameraApiPigeonCodec()
    }
    /** Sets up an instance of `CameraHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CameraHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.camera_app.CameraHostApi.listCameras$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.listCameras())
              } catch (exception: Throwable) {
                CameraApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.camera_app.CameraHostApi.requestCameraPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.requestCameraPermission())
              } catch (exception: Throwable) {
                CameraApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.camera_app.CameraHostApi.setPreviewCameras$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val cameraIdsArg = args[0] as List<String>
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.setPreviewCameras(cameraIdsArg)
                listOf(null)
              } catch (exception: Throwable) {
                CameraApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.camera_app.CameraHostApi.startBuffering$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val cameraIdsArg = args[0] as List<String>
            val settingsArg = args[1] as SosCaptureSettings
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.startBuffering(cameraIdsArg, settingsArg)
                listOf(null)
              } catch (exception: Throwable) {
                CameraApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.camera_app.CameraHostApi.getBufferingSeconds$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.getBufferingSeconds())
              } catch (exception: Throwable) {
                CameraApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.camera_app.CameraHostApi.triggerSos$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.triggerSos())
              } catch (exception: Throwable) {
                CameraApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.camera_app.CameraHostApi.stopBuffering$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.stopBuffering()
                listOf(null)
              } catch (exception: Throwable) {
                CameraApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.camera_app.CameraHostApi.releaseCameras$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.releaseCameras()
                listOf(null)
              } catch (exception: Throwable) {
                CameraApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
